# Generated by Django 5.1.4 on 2025-01-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoBu_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='CoBu', max_length=225),
        ),
    ]
