# Generated by Django 5.1.4 on 2025-01-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoBu_post', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='platform',
            field=models.CharField(choices=[('PC', 'PC'), ('Playstation', 'Playstation'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo')], default='PC', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
