# Generated by Django 5.1.4 on 2025-01-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoBu_post', '0007_post_platform_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='This is a default body content.'),
        ),
    ]
